/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.IOException;
import java.io.InputStream;


public class App {

    public static void main(String[] args) {
        Quotes q = new Quotes();
        try {
            InputStream is = q.readFileFromResources("quotes.json");
            q.openFileReaderOnResourceStream(is);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
